name: CSV scheduled update

on:
  schedule:
  - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          setup-python: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r src/requirements.txt
      - name: Synchronize the csv file with an up-to-date one
        run: |
          cd src
          python download.py
          cd ..
      - name: convert json to url list
        run: |
          cat "./csv/kdb-$(date +%Y%m%d).csv" | tail -n +2 | cut -d ',' -f 1 | tr -d '"' | sed -e 's;\(.*\);https://kdb.tsukuba.ac.jp/syllabi/2021/\1/jpn/\n out=\1.html;g' > list
      - name: download url list
        run: |
          cd syllabus
          aria2c -i ../list -j 100
      - name: Pull and Commit
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add syllabus
          git commit -m "update syllabus: $(date +%Y%m%d)"
          git pull origin master
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_ADMIN_TOKEN }}
          branch: ${{ github.ref }}
