name: Syllabus scheduled update

on:
  schedule:
  - cron: '0 15 * * 6'
  workflow_dispatch:

jobs:
  update:
    environment: actions
    runs-on: ubuntu-latest
    env:
        TZ: Asia/Tokyo
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Run download script
        run: |
          wget -O download.sh https://git.io/JinJf
          chmod +x download.sh
          ./download.sh
          rm download.sh
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Sceduled update of syllabus data (${{ steps.date.outputs.date }})
          branch: update_${{ steps.date.outputs.date }}
          author: GitHub Action <action@github.com>
          committer: GitHub Action <action@github.com>
          commit-message: |
            update csv: ${{ steps.date.outputs.date }}
          labels: automated pr
          delete-branch: true
