name: Syllabus update

on:
  schedule:
  - cron: '0 0 * * 0'
  workflow_dispatch:

env:
  TZ: 'Asia/Tokyo'

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          setup-python: ${{ matrix.python-version }}
      - name: Synchronize the csv file with an up-to-date one
        run: |
          chmod +x ./download.sh
          ./download.sh
      - name: Pull and Commit
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add syllabus
          git commit -m "update syllabus: $(date +%Y%m%d)"
          git pull origin master
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_ADMIN_TOKEN }}
          branch: ${{ github.ref }}
